apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "activemq.fullname" . }}
  labels:
    app: {{ template "activemq.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "activemq.fullname" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: activemq
        image: "{{ .Values.activemq.image.repository }}:{{ .Values.activemq.image.tag }}"
        imagePullPolicy: {{ .Values.activemq.image.pullPolicy }}
        env:
        - name: ACTIVEMQ_CONFIG_MINMEMORY
          value: "{{ .Values.activemq.image.configMinMemory }}"
        - name: ACTIVEMQ_CONFIG_MAXMEMORY
          value: "{{ .Values.activemq.image.configMaxMemory }}"
        ports:
        - name: openwire
          containerPort: {{ .Values.activemq.services.broker.ports.internal.openwire | default 61616 }}
        - name: amqp
          containerPort: {{ .Values.activemq.services.broker.ports.internal.amqp | default 5672 }}
        - name: web-console
          containerPort: {{ .Values.activemq.services.webConsole.ports.internal.webConsole | default 8161 }}
        readinessProbe:
          tcpSocket:
            port: {{ .Values.activemq.services.broker.ports.internal.openwire | default 61616 }}
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: {{ .Values.activemq.services.broker.ports.internal.openwire | default 61616 }}
          initialDelaySeconds: 5
          periodSeconds: 25
        resources:
{{ toYaml .Values.activemq.resources | indent 12 }}
