apiVersion: v1
kind: Service
metadata:
  name: {{ template "activemq.fullname" . }}-broker
  labels:
    app: {{ template "activemq.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.activemq.services.broker.type }}
  ports:
  - port: {{ .Values.activemq.services.broker.ports.external.openwire | default 61616 }}
    targetPort: {{ .Values.activemq.services.broker.ports.internal.openwire | default 61616 }}
    name: openwire
    protocol: TCP
  - port: {{ .Values.activemq.services.broker.ports.external.amqp | default 5672 }}
    targetPort: {{ .Values.activemq.services.broker.ports.internal.amqp | default 5672 }}
    name: amqp
    protocol: TCP
  selector:
    app: {{ template "activemq.fullname" . }}
    release: {{ .Release.Name }}