# Default values for alfresco-insight-zeppelin.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Define the alfresco-insight-zeppelin properties to use in the k8s cluster
# This is chart will be installed as part of Alfresco Insight Engine
replicaCount: 1
image:
  repository: quay.io/alfresco/insight-zeppelin
  tag: "1.0.0-RC1"
  pullPolicy: Always
  internalPort: 9090
service:
  name: zeppelin
  type: ClusterIP
  externalPort: 80
ingress:
  path: /zeppelin
# The parent chart will set the values for "repository.host" and "repository.port"
repository: {}