# Defines the ingress for the digital workspace app
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "digital-workspace.shortname" . }}
  labels:
    component: digitalWorkspaceApplication
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .Values.ingress.maxUploadSize }}
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: {{ .Values.ingress.path }}
        backend:
          serviceName: {{ template "digital-workspace.shortname" . }}
          servicePort: {{ .Values.service.externalPort }}