{{- if .Values.persistence.enabled -}}
{{- if .Values.persistence.efs.enabled }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-{{ template "alfresco-infrastructure.fullname" . }}
provisioner: alfresco.com/efs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-{{ template "alfresco-infrastructure.fullname" . }}
spec:
  capacity:
    storage: {{ .Values.persistence.baseSize | quote }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: {{ .Values.persistence.reclaimPolicy | default "Recycle" }}
  nfs:
    server: "{{ .Values.persistence.efs.dns }}"
    path: "{{ .Values.persistence.efs.path }}"
  storageClassName: efs-{{ template "alfresco-infrastructure.fullname" . }}
---
{{- end }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: alfresco-volume-claim
spec:
  accessModes:
  {{ if .Values.persistence.efs.enabled }}
    - ReadWriteMany
  storageClassName: efs-{{ template "alfresco-infrastructure.fullname" . }}
  {{ else }}
    - ReadWriteOnce
  {{ end }}
  resources:
    requests:
      storage: {{ .Values.persistence.baseSize | quote }}
{{- end -}}