apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "aps.fullname" . }}-aps
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - http:
      paths:
      - path: {{ .Values.ingress.path }}
        backend:
          serviceName: {{ template "aps.fullname" . }}-aps
          servicePort: {{ .Values.processEngine.service.externalPort }}
