appVersion: 6.1.0-RC4
description: A Helm chart for deploying Alfresco Content Services
home: https://www.alfresco.com
icon: https://avatars0.githubusercontent.com/u/391127?s=200&v=4
keywords:
- content
- content services
- alfresco
- alfresco content services
name: alfresco-content-services
sources:
- https://github.com/Alfresco/acs-deployment
version: 1.1.8
