dependencies:
  - name: rabbitmq-ha
    version: ^0.1.0
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: alfresco-infrastructure.rabbitmq-ha.enabled
  - name: activemq
    version: ^0.1.0
    repository: https://kubernetes-charts.alfresco.com/incubator
    condition: alfresco-infrastructure.activemq.enabled
  - name: alfresco-identity-service
    version: ^0.3.8
    condition: alfresco-infrastructure.alfresco-identity-service.enabled
    repository: https://kubernetes-charts.alfresco.com/incubator
  - name: alfresco-activiti-cloud-registry
    version: ^0.1.0
    condition: alfresco-infrastructure.alfresco-activiti-cloud-registry.enabled
    repository: https://kubernetes-charts.alfresco.com/incubator
  - name: alfresco-api-gateway
    version: 0.1.1
    condition: alfresco-infrastructure.alfresco-api-gateway.enabled
    repository: https://kubernetes-charts.alfresco.com/incubator
  - name: nginx-ingress
    condition: alfresco-infrastructure.nginx-ingress.enabled
    repository: https://kubernetes-charts.storage.googleapis.com/
    version: 0.14.0
